name: philips_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  google_nav_bar: ^5.0.6
  flutter_animated_button: ^2.0.3
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0
  onboarding_animation: ^0.0.3
  google_fonts: ^6.1.0
  folding_cell: "^1.0.2"
  flip_card: ^0.7.0
  neon_widgets: ^2.0.0
  flutter_card_swiper: ^7.0.0
  audioplayers: ^5.2.1
  get: ^4.6.6
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/images/logo/philips_shield.png
      - assets/images/select_action_page_images/HowWeHear.png
      - assets/images/select_action_page_images/hearing_disorders.png
      - assets/images/select_action_page_images/Hearing_Lost.png
      - assets/images/select_action_page_images/Hearing_Tests.png
      - assets/images/select_action_page_images/philips_hearlink.png
      - assets/images/select_action_page_images/HearingLost_Simulator.png
      - assets/images/simulator_page_image/forest.png
      - assets/images/simulator_page_image/ocean_waves.png
      - assets/images/simulator_page_image/restaurant.png
      - assets/images/hearing_aid/oticon_2.jpg
      - assets/images/icons/home.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Dubia
       fonts:
         - asset: assets/fonts/Dubai-Light.ttf
           weight: 200
         - asset: assets/fonts/Dubai-Regular.ttf
           weight: 400
         - asset: assets/fonts/Dubai-Medium.ttf
           weight: 600
         - asset: assets/fonts/Dubai-Bold.ttf
           weight: 800

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
