// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQkTbLSHTTyQh57_TuxnbkoJsrVyTLMEU',
    appId: '1:809607936703:web:d448f18ef62ad0bcb9a40a',
    messagingSenderId: '809607936703',
    projectId: 'rapid-project-1494b',
    authDomain: 'rapid-project-1494b.firebaseapp.com',
    storageBucket: 'rapid-project-1494b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVctgxsZkNJR-u1-KPuAnVkaDsH9mWGPI',
    appId: '1:809607936703:android:cbdc39b71ffcf397b9a40a',
    messagingSenderId: '809607936703',
    projectId: 'rapid-project-1494b',
    storageBucket: 'rapid-project-1494b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59A24qOwey6ucmwo5VDCFx6rc3_uMp1k',
    appId: '1:809607936703:ios:a945929e54e3a10fb9a40a',
    messagingSenderId: '809607936703',
    projectId: 'rapid-project-1494b',
    storageBucket: 'rapid-project-1494b.appspot.com',
    iosBundleId: 'com.example.philips1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59A24qOwey6ucmwo5VDCFx6rc3_uMp1k',
    appId: '1:809607936703:ios:2f798a5f684abaf8b9a40a',
    messagingSenderId: '809607936703',
    projectId: 'rapid-project-1494b',
    storageBucket: 'rapid-project-1494b.appspot.com',
    iosBundleId: 'com.example.philips1.RunnerTests',
  );
}
